---
# tasks file for sonarqube
# control the task flow here
#
- name: Install Java
  include_tasks: java.yml

- name: Setup PostgreSQL
  include_tasks: postgres.yml



- name: Install and configure SonarQube
  include_tasks: sonarqube.yml
- name: Apply kernel settings required for SonarQube
  include_tasks: sysctl.yml