---
# handlers file for sonarqube
# /etc/systemd/system/sonarqube.service


- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart postgresql
  service:
    name: postgresql
    state: restarted
    enabled: yes
  when: ansible_os_family == "Debian"

- name: enable sonarqube
  systemd:
    name: sonarqube
    state: started
    enabled: yes

- name: restart sonarqube
  systemd:
    name: sonarqube
    state: restarted
    enabled: yes
  when: ansible_facts['os_family'] == "Debian"



