---
# defaults file for sonarqube
# sonarqube vsersion, user, group, port is defined here
sonarqube_version: "25.9.0.112764"
sonarqube_user: sonar
sonarqube_group: sonar
sonarqube_port: 9000

# java version definitions
java_version: "21"
# java packages based on os family
java_package:
  Debian: openjdk-{{ java_version }}-jdk
  #centos: openjdk-21-jdk # removed centos as it is a rhel based system
  RedHat: java-{{ java_version }}-openjdk
java_pkg: "{{ java_package[ansible_os_family]}}"
sudo_group: "{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"


sonarqube_java_home_debian: "/usr/lib/jvm/java-{{ java_version}}-openjdk-amd64"
sonarqube_java_home_redhat: "/usr/lib/jvm/java-{{ java_version}}-openjdk"
sonarqube_install_dir: /opt/sonarqube
# https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-25.8.0.112029.zip
sonarqube_download_url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip
# terminal password for sonarqube user
sonarqube_user_password: '12345'
# password hash for sonarqube user
sonarqube_password_hash: "$6$C0M5VJ9U$0Wk5xQ7v1kR9fL8sQzPqVnF1h8TnP2LwZqF5HhK1J8sQ2R7P0B6Y"  
# postgres user and db creation variables
# unused variables, might need for private ec2's
# postgres_host: localhost
# postgres_superuser: postgres     # postgres is runnning on localhost (same ec2 instance)
# postgres config, user, db, password
db_user: sonarqube_3
db_password: '12345'
db_name: sonarqube_3
db_port: 5432
postgresql_version: "18"

# Firewall configuration
# Set to false to skip UFW enable during playbook (prevents SSH lockout during execution)
# Rules will still be added (SSH + SonarQube), but UFW won't be enabled
# You can enable UFW manually after playbook completes: sudo ufw enable
# Default: false (recommended for CI/CD pipelines to prevent SSH lockout)
enable_ufw_during_playbook: false

