---
# defaults file for sonarqube
# sonarqube vsersion, user, group, port is defined here
sonarqube_version: "25.9.0.112764"
sonarqube_user: sonar
sonarqube_group: sonar
sonarqube_port: 9000

# java packages based on os family
java_package:
  ubuntu: openjdk-21-jdk
  centos: java-21-openjdk-devel
  debian: openjdk-21-jdk




# binaries link is currnetly not working
sonarqube_download_url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip


# postgres user and db creation variables
# unused variables, might need for private ec2's
# postgres_host: localhost
# postgres_superuser: postgres     # postgres is runnning on localhost (same ec2 instance)
# postgres config, user, db, password
db_user: sonarqube_3
db_password: '12345'
db_name: sonarqube_3

postgresql_version: "18"

